---
name: "Root.io Image Remediation"
description: "Runs the Root.io remediation client to analyze and remediate container images."
author: "Root.io"
branding:
  icon: "shield"
  color: "green"

inputs:
  image_reference:
    description: "The image reference to remediate in the format of 'registry/image:tag'."
    required: true
  org_id:
    description: "The organization ID of the organization where the image is stored."
    required: true
  api_token:
    description: "The API token used to authenticate with the Root.io API."
    required: true
  registry_credentials_id:
    description: "The ID of the registry credentials used to pull the image."
    required: true
  output_path:
    description: "The path where remediation artifacts will be stored."
    required: false
    default: "${{ github.workspace }}/remediation-output"

outputs:
  process_status:
    description: "The process status from the scan summary"
  result_image:
    description: "The user instrumented image from the remediation result"
  remediation_status:
    description: "The status from the image remediation"
  id:
    description: "The ID from the scan summary"
  remediation_decision:
    description: "The decision from the image remediation"
  remediation_error:
    description: "The error from the image remediation"
  image_created:
    description: "Boolean indicating if a result image was created"

runs:
  using: "composite"
  steps:
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Create output directory if it doesn't exist
      shell: bash
      run: |
        mkdir -p ${{ inputs.output_path }}

    - name: Run Remediation Client
      shell: bash
      run: |
        docker run --rm \
          -v ${{ inputs.output_path }}:/output \
          public.ecr.aws/rootio/remediation-client:latest \
          ${{ inputs.org_id }} \
          ${{ inputs.api_token }} \
          ${{ inputs.registry_credentials_id }} \
          ${{ inputs.image_reference }} \
          /output

    - name: Generate UUID
      id: uuid
      shell: bash
      run: echo "id=$(uuidgen | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Parse results and set outputs
      shell: bash
      run: |
        # Initialize variables
        process_status=""
        id=""
        result_image=""
        remediation_status=""
        remediation_decision=""
        remediation_error=""
        
        # Find the actual JSON files (they have prefixed names)
        scan_summary_file=$(find "${{ inputs.output_path }}" -name "*_scan_summary.json" | head -1)
        image_remediation_file=$(find "${{ inputs.output_path }}" -name "*_image_remediation.json" | head -1)
        
        # Parse scan_summary.json (object format)
        if [ -f "${scan_summary_file}" ]; then
          process_status=$(jq -r '.process_status // ""' "${scan_summary_file}")
          id=$(jq -r '.id // ""' "${scan_summary_file}")
        fi
        
        if [ -f "${image_remediation_file}" ] && [ $(jq 'length' "${image_remediation_file}") -gt 0 ]; then
          result_image=$(jq -r '.[0].user_instrumented_image // ""' "${image_remediation_file}")
          remediation_status=$(jq -r '.[0].status // ""' "${image_remediation_file}")
          remediation_decision=$(jq -r '.[0].decision // ""' "${image_remediation_file}")
          remediation_error=$(jq -r '.[0].error // ""' "${image_remediation_file}")
        fi
        
        # Set all outputs
        echo "process_status=${process_status}" >> $GITHUB_OUTPUT
        echo "id=${id}" >> $GITHUB_OUTPUT
        echo "result_image=${result_image}" >> $GITHUB_OUTPUT
        echo "remediation_status=${remediation_status}" >> $GITHUB_OUTPUT
        echo "remediation_decision=${remediation_decision}" >> $GITHUB_OUTPUT
        echo "remediation_error=${remediation_error}" >> $GITHUB_OUTPUT
        
        # Set image_created based on result_image
        if [ -n "${result_image}" ] && [ "${result_image}" != "null" ] && [ "${result_image}" != "" ]; then
          echo "image_created=true" >> $GITHUB_OUTPUT
        else
          echo "image_created=false" >> $GITHUB_OUTPUT
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: remediation-results-${{ github.run_id }}-${{ steps.uuid.outputs.id }}
        path: ${{ inputs.output_path }}/*.json
        if-no-files-found: error
